// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSok0F7Ewtq92kLX14UB2r_d3wQnowOCM',
    appId: '1:980816351869:web:355d38d36216ab6f8c1714',
    messagingSenderId: '980816351869',
    projectId: 'contact-tracing-7ee48',
    authDomain: 'contact-tracing-7ee48.firebaseapp.com',
    storageBucket: 'contact-tracing-7ee48.appspot.com',
    measurementId: 'G-K2MLZYJZVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk67BKIDRCvQaIVFeQVFQLb6td_GFMy-U',
    appId: '1:980816351869:android:b825f43ad61e3dd28c1714',
    messagingSenderId: '980816351869',
    projectId: 'contact-tracing-7ee48',
    storageBucket: 'contact-tracing-7ee48.appspot.com',
  );
}
